# Dockerfile.frontend
FROM nginx:stable-alpine

# Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy static files
COPY public /usr/share/nginx/html

# Expose default http port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
